### ISSUE TITLE
Make NECOFS WMS endpoints discoverable in IOOS catalog

### ISSUE THREAD

**Issue by rsignell-usgs** [neracoos-open/DMAC#1]
As mentioned on the 2017-04-05 NERACOOS DMAC call, I'd like to get NECOFS WMS endpoints discoverable in the IOOS catalog before the end of April.   

The use case I'm trying to enable is to be able to view NECOFS data in TerriaJS. 

For a live demo of what I'd like to enable, try this [**example showing PACIOOS ROMS data in TerriaJS**](http://tinyurl.com/k95ab6z). 

Screenshot here: 
![2017-04-05_12-04-48](https://cloud.githubusercontent.com/assets/1872600/24715127/71919b48-19f8-11e7-8eb2-99273f2fbf9a.jpg)

**Comment by rsignell-usgs** [comment]
To enable discoverable WMS endpoints for NECOFS in the IOOS catalog, we need:
- [x] ncWMS2 enabled at SMAST
- [ ] SMAST ncWMS2 configured with the same datasets currently discovered on IOOS catalog
- [ ] SMAST thredds server catalog modified to point to the SMAST ncWMS2 services

I will work on these with Andre Schmidt (@ackschmidt) at SMAST on implementing these.

**Comment by rsignell-usgs** [comment]
According to @kwilcox, we just need to modify the list of services in the thredds catalog (like `forecasts.xml`) to add the non-THREDDS WMS service, like this:
```
  <service name="allServices" serviceType="Compound" base="">
    <service name="ncdods" serviceType="OpenDAP" base="/thredds/dodsC/"/>
    <service name="HTTPServer" serviceType="HTTPServer" base="/thredds/fileServer/"/>
    <service name="ncml" serviceType="NCML" base="/thredds/ncml/"/>
    <service name="iso" serviceType="ISO" base="/thredds/iso/"/>
    <service name="uddc" serviceType="UDDC" base="/thredds/uddc/"/>
    <service name="wms" serviceType="WMS" base="http://www.smast.umassd.edu:8080/ncWMS2/wms" />  
  </service>
```

**Comment by ebridger** [comment]
👍

**Comment by rsignell-usgs** [comment]
@ackschmidt made the changes for the GOM3 Forecast, and we can now see [the WMS service endpoint in the THREDDS catalog](
http://www.smast.umassd.edu:8080/thredds/forecasts.html?dataset=gom3_nocache)
and we can also see that WMS endpoint in the [ISO record](http://www.smast.umassd.edu:8080/thredds/iso/FVCOM/NECOFS/Forecasts/NECOFS_GOM3_FORECAST.nc?catalog=http%3A%2F%2Fwww.smast.umassd.edu%3A8080%2Fthredds%2Fforecasts.html&dataset=gom3_nocache) so it should get picked up by the [IOOS Catalog](https://data.ioos.us/dataset?q=necofs) tonight!

**Comment by rsignell-usgs** [comment]
Now that it works for the GOM3 forecast we just need to add the other datasets to the ncWMS2 server and modify their `<dataset>` entries in the `forecasts.xml` file.

**Comment by ebridger** [comment]
Noticed some errors in my WAF_generator.py script from some of the NECOFS TDS catalogs. This is the root catalog I use: http://www.smast.umassd.edu:8080/thredds/forecasts.html
But some of the Hi-Res forecasts, Boston, Scituate and Global, the ncISO links give an internal server error.
http://www.smast.umassd.edu:8080/thredds/iso/FVCOM/NECOFS/Forecasts/NECOFS_FVCOM_OCEAN_SCITUATE_FORECAST.nc?catalog=http%3A%2F%2Fwww.smast.umassd.edu%3A8080%2Fthredds%2Fforecasts.html&dataset=scituate_nocache

**Comment by rsignell-usgs** [comment]
I just tried a NECOFS harvest with Docker:
```
do_crawl.sh harvest_necofs.py
```
`do_crawl.sh`:
```
#!/bin/bash
# Usage: do_crawl <harvest>.py
docker run --rm -v $(pwd)/$1:/srv/harvest.py -v $(pwd)/iso:/srv/iso  axiom/thredds_iso_harvester
```
`harvest_necofs.py`:
```
from thredds_iso_harvester.harvest import ThreddsIsoHarvester
from thredds_crawler.crawl import Crawl

skip = Crawl.SKIPS
select = ['.*']

ThreddsIsoHarvester(catalog_url="http://www.smast.umassd.edu:8080/thredds/foreca
sts.html",
    skip=skip, select=select,
    out_dir="/srv/iso/necofs")
```

The files that get produced are:
```
gom3_nocache.iso.xml     
massbay_nocache.iso.xml   
necofs_met.iso.xml
hampton_nocache.iso.xml
necofs_gom3_wave.iso.xml
```
So everything except Boston.  I'll look into this.

**Comment by rsignell-usgs** [comment]
@ebridger , you might find the above approach appealing to manage the harvests going forward?  Let someone else maintain the crawling code, python environment, etc

Could you please reharvest the ISO records, and then tell the IOOS registry to gobble them up?

We just enabled the WMS services on more datasets.

**Comment by rsignell-usgs** [comment]
We're rolling now!   We've got one NECOFS WMS endpoint:
![2017-04-07_15-13-47](https://cloud.githubusercontent.com/assets/1872600/24815972/166a08be-1ba5-11e7-88dc-5abef29e58a2.png)

**Comment by rsignell-usgs** [comment]
The next harvest should return 8 NECOFS records instead of 5 (I fixed the ISO issues by removing variables that depended on siglev -- the siglev dimension had already been removed!).

**Comment by ebridger** [comment]
Done.  Got 8 iso records. 

`awsgmri:eric:~/WAF/UMASSD-SMAST/Forecasts/iso> ls -1 *.xml`

```
NECOFS_Boston_Forecast.xml
NECOFS_Global_Forecast.xml
NECOFS_GOM3_Forecast.xml
NECOFS_GOM3_Wave_Forecast.xml
NECOFS_Hampton_Forecast.xml
NECOFS_MASSBAY_Forecast.xml
NECOFS_MET_Forecast.xml
NECOFS_Scituate_Forecast.xml
```

But only 6 with WMS endpoints.

`awsgmri:eric:~/WAF/UMASSD-SMAST/Forecasts/iso> grep -il wms *.xml`

```
NECOFS_Boston_Forecast.xml
NECOFS_GOM3_Forecast.xml
NECOFS_GOM3_Wave_Forecast.xml
NECOFS_Hampton_Forecast.xml
NECOFS_MASSBAY_Forecast.xml
NECOFS_Scituate_Forecast.xml
```

**Comment by rsignell-usgs** [comment]
@ebridger, I didn't enable the WMS service on the MET data yet because it's not unstructured, and the global is having some strange issue, which I have raised with the ncWMS2 gang in  https://github.com/Reading-eScience-Centre/edal-java/issues/84

I'm going to close this one for now though.  Mission accomplished on the WMS!

**Comment by rsignell-usgs** [comment]
I tested the NECOFS WMS services provided by ncWMS2 in TerriaJS and was getting horrific performance (like 5 minutes to load a map or the entire domain), and then I remembered that the ncWMS2 installed at SMAST was from August 2016 and didn't contain this AMAZING performance enhancement to ncWMS2
https://github.com/neracoos-open/NFWF/issues/13#issuecomment-256006054

So after upgrading SMAST ncWMS2 to the most recent version:
https://github.com/Reading-eScience-Centre/ncwms/releases/download/ncwms-2.2.6/ncWMS2.war

It now only takes a few seconds to load NECOFS forecast data maps:
![2017-04-11_6-22-36](https://cloud.githubusercontent.com/assets/1872600/24904711/553d4fd8-1e7f-11e7-888d-601c777eaae7.jpg)

Try for yourself here:
http://tinyurl.com/lyuz5lf

And try browsing NECOFS datasets dynamically in TerriaJS using the IOOS Catalog here:
http://gamone.whoi.edu/terriajs/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/csw_necofs.json
(you need to go to "add data" and click on "csw")

**Comment by rsignell-usgs** [comment]
Also, you can try browsing NECOFS datasets dynamically in TerriaJS using the IOOS Catalog here:
http://gamone.whoi.edu/terriajs/#clean&proxy/_60s/https://raw.githubusercontent.com/USGS-CMG/terriajs-dive/master/examples/csw_necofs.json
You need to go to "add data" and click on "csw", as shown here:
![2017-04-11_6-35-42](https://cloud.githubusercontent.com/assets/1872600/24905248/4ed6cfdc-1e81-11e7-8d92-a4dae7c22226.png)
