### ISSUE TITLE
Harvesting of NECOFS ISO data

### ISSUE THREAD

**Issue by rsignell-usgs** [neracoos-open/DMAC#2]
I was looking at the [IOOS registry](https://registry.ioos.us/harvests) harvest of "NERACOOS NECOFS WAF" and when I checked (at 5pm EDT), it says "last harvested 21 hours ago", so it would seem that the ISO records from the NECOFS THREDDS server get harvested at 8PM EDT (0000 UTC).

But since the NECOFS models run overnight, a much better time to harvest the ISO records would be in the morning after the models have completed.  

From looking at the NECOFS NetCDF file times at `www.smast.umassd.edu:/http/www/CODFISH/Data/FVCOM/NECOFS/Forecasts` and it appears everything runs overnight and is done by 08:30 ET: 
```
-rw-r--r-- 1 1295 400   52954804 Apr  6 05:08 NECOFS_MET_FORECAST.nc
-rw-r--r-- 1 1295 400 9596350092 Apr  6 05:19 NECOFS_GOM3_FORECAST.nc
-rw-r--r-- 1 1295 400  291188756 Apr  6 07:20 NECOFS_WAVE_FORECAST.nc
-rw-r--r-- 1 1295 400 4285859828 Apr  6 08:17 NECOFS_FVCOM_OCEAN_MASSBAY_FORECAST.nc
```
So I propose:
* 8:45AM EDT (1245 UTC):  harvest the ISO records from SMAST THREDDS into http://www.neracoos.org/WAF/UMASSD-SMAST/Forecasts/iso/
* 8:55AM EDT (1255 UTC):  have the IOOS registry harvest the records from http://www.neracoos.org/WAF/UMASSD-SMAST/Forecasts/iso/

That way by 9EDT (1300 UTC) we would have up to date NECOFS metadata in the IOOS catalog. 

@ebridger , can we make that happen?

**Comment by ebridger** [comment]
Done. I  run this update twice. 8:45 and now 19:45

**Comment by rsignell-usgs** [comment]
@ebridger , you should be able to login to https://registry.ioos.us and change the harvest time for any data owned by NERACOOS.  Or issue a manual harvest. 

Isn't that right @mwengren and @lukecampbell?

**Comment by lukecampbell** [comment]
The job to reharvest all metadata is done daily at midnight ZULU, I believe but it takes a while to harvest everything in the registry so I don't know when exactly it gets reharvested.

**Comment by rsignell-usgs** [comment]
@lukecampbell , so authorized folks can manually harvest their WAFs, but they can't change the time (or frequency) with which they are automatically harvested?

**Comment by lukecampbell** [comment]
Not yet. Initially we allowed for the harvest period to be custom, but I couldn't get custom periods to play nicely with cron jobs. It's on our list to support as we continue to develop the registry.

**Comment by rsignell-usgs** [comment]
Since most of the IOOS models run at night, I think we could improve on the default daily 0000 UTC since that's 8pm East Coast, 2pm Hawaii.   

So how about setting the default to 1800 UTC, which is 8:00am in Hawaii, 2:00pm East Coast?

**Comment by ebridger** [comment]
👍

**Comment by lukecampbell** [comment]
Could you create a new issue tasking me to change the cron time and assign me to it?

**Comment by rsignell-usgs** [comment]
Actually, wouldn't the best solution be for @ebridger to just add a line at the end of his script that he uses to create his ISO records that would use the freshly minted [IOOS Registry API](https://github.com/ioos/catalog-harvest-registry/pull/99) to force a refresh there?   

@lukecampbell can you give an example of what this line would look like?

**Comment by mwengren** [comment]
@lukecampbell Let's add this documentation/code examples to the [IOOS Catalog Docs Site](https://ioos.github.io/catalog/) when ready.

**Comment by rsignell-usgs** [comment]
closing since this is basically fixed now, and can be enhanced when https://github.com/ioos/catalog-harvest-registry/issues/100 is done.
